name: Musicizer
description: an app that connects music with fitness using tempo-modification.

dependencies:
  
  google_nav_bar: ^2.2.0
  getflutter: ^1.0.11
  just_audio: ^0.1.10
  youtube_explode_dart: ^1.7.0
  flutter_launcher_icons:  ^0.7.5
  sensors: ^0.4.2+2
  color: any
  introduction_screen: ^1.0.9
  conditional_builder: ^1.0.2
  animate_do: ^1.7.2
  flappy_search_bar: ^1.7.2
  fl_chart: ^0.10.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+3
  auto_size_text: ^2.1.0

flutter_blue: 0.6.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
flutter:

  uses-material-design: true

  assets:
    #- assets/musicizer.png
    #- assets/song.mp3
    #- assets/time.jpg
    - assets/