library musicizer.globals;
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:just_audio/just_audio.dart';
import 'intensity_data.dart';
String username = "";
String resetEmail = "";
int musicpoints = 0;
int musicpointsEarned = 0;
Map<String, double> location = {};
double speed;
int runningPage = 0;
double level = 1.0;
Map<String, String> path;
bool signOutRequest = true;
bool powersaveMode;
double brightness;
String audioStreamUrl;
List audioStreamUrls = [];
List<Video> playlist = [];
Video video;
int minutes = 60;
int page = 0;
var pfpUrl = "";
bool playing = false;
bool started = false;
String userId;
bool tempFill = false;
bool inSpeed = false;
bool stop = false;
var advancedPlayer;
List<IntensityData> data = [];
int totalMinutes = 0;
int onPace = 0;
var navBar;
int index = 0;
var loadingSongs = false;
bool switch1 = true;
List leaderboard = [];
List<int> indexArr = [];
var shuffle = false;